version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  redis:
    image: redis:6
    volumes:
      - ./data/redis:/data
