name: mad_libs
description: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaa

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-BlackItalic.ttf
          weight: 900
          style: italic
