import 'story.dart';
import 'text.dart';

var breakingWeatherReport = StoryBuilder(title: "Breaking Weather Report")
    .text("We interrupt this ")
    .word(WordType.adjective)
    .text(" broadcast to bring you a ")
    .word(WordType.adjective)
    .text(" news bulletin. Hurricane ")
    .word(WordType.name, "Name (female)")
    .text(", with gusting ")
    .word(WordType.pluralNoun)
    .text(" clocked at ")
    .word(WordType.number)
    .text(" miles per hour, is hammering the ")
    .word(WordType.adverb)
    .text(" populated Florida coast. This ")
    .word(WordType.adjective)
    .text("storm has left ")
    .word(WordType.adjective)
    .text(" devastation in its wake. The National ")
    .word(WordType.noun)
    .text(
        " Bureau reports that in Miami, windows have been blown out of fifty high-rise ")
    .word(WordType.pluralNoun)
    .text(", showering the streets below with pieces of broken ")
    .word(WordType.pluralNoun)
    .text(". The howling winds have reduced a newly built ")
    .word(WordType.verbIng)
    .text(" center to ")
    .word(WordType.pluralNoun)
    .text(". Police report a seven-ton railroad ")
    .word(WordType.noun)
    .text(" was lifted off its track and sent ")
    .word(WordType.verbIng)
    .text(" into a three story ")
    .word(WordType.noun)
    .text(
        ". Fortunately, there have been no casualties. Nevertheless, the Governor has declared a ")
    .word(WordType.noun)
    .text(" of emergency and advised all ")
    .word(WordType.pluralNoun)
    .text(" to seek safety in a ")
    .word(WordType.noun)
    .text(" shelter. And now back to your ")
    .word(WordType.noun)
    .text(" in progress")
    .pack();
